import { migrateSceneDocument, type DeckDocumentV2 } from './deck.js'
import { createGripGunPrototypeScene } from './gripgun-scene.js'
import type { SceneElement, SceneSlide, SceneTrack } from './schema.js'

const transform = (x: number, y: number, width: number, height: number, zIndex: number, opacity = 1) => ({ x, y, width, height, rotation: 0, opacity, zIndex })
const text = (id: string, content: string, x: number, y: number, width: number, size: number, color = '#0f172a', opacity = 1): SceneElement => ({ id, type: 'text', content, transform: transform(x, y, width, 80, 10, opacity), style: { color, fontSize: size, fontWeight: 800, lineHeight: 1.12 }, accessibilityLabel: content })
const card = (id: string, content: string, x: number, y: number, width: number, height: number, color: string, opacity = 0): SceneElement => ({ id, type: 'shape', content, transform: transform(x, y, width, height, 4, opacity), style: { background: '#ffffff', border: `3px solid ${color}`, borderRadius: 28, color, fontSize: 24, fontWeight: 800, boxShadow: `0 20px 50px ${color}22` }, accessibilityLabel: content })
const image = (id: string, assetId: string, x: number, y: number, width: number, height: number, opacity = 0): SceneElement => ({ id, type: 'image', assetId, transform: transform(x, y, width, height, 2, opacity), style: { borderRadius: 34, border: '3px solid rgba(255,255,255,.88)', boxShadow: '0 28px 70px rgba(15,23,42,.28)' }, accessibilityLabel: assetId })
const connector = (id: string, fromId: string, fromAnchor: 'left' | 'right' | 'top' | 'bottom' | 'center', toId: string, toAnchor: 'left' | 'right' | 'top' | 'bottom' | 'center', color: string): SceneElement => ({ id, type: 'connector', transform: transform(0, 0, 24, 26, 6, 0), connector: { from: { elementId: fromId, anchor: fromAnchor }, to: { elementId: toId, anchor: toAnchor } }, style: { background: color, pathProgress: 0, borderRadius: 99 }, accessibilityLabel: 'flow connector' })
const fade = (id: string, elementId: string, start: number, end: number): SceneTrack => ({ id, elementId, property: 'opacity', keyframes: [{ at: start, value: 0, easing: 'linear' }, { at: end, value: 1, easing: 'ease-out' }] })
const appear = (id: string, elementId: string, at: number): SceneTrack => ({ id, elementId, property: 'opacity', keyframes: [{ at: Math.max(0, at - .001), value: 0, easing: 'linear' }, { at, value: 1, easing: 'linear' }] })
const draw = (id: string, elementId: string, start: number, end: number): readonly SceneTrack[] => [
  { id, elementId, property: 'pathProgress', keyframes: [{ at: start, value: 0, easing: 'linear' }, { at: end, value: 1, easing: 'ease-out' }] },
  { id: `${id}-visible`, elementId, property: 'opacity', keyframes: [{ at: start, value: 0, easing: 'linear' }, { at: end, value: 1, easing: 'ease-out' }] },
]
const pulse = (id: string, elementId: string, start: number): SceneTrack => ({ id, elementId, property: 'style.scale', keyframes: [{ at: start, value: 0.86, easing: 'ease-out' }, { at: start + .18, value: 1.12, easing: 'ease-out' }, { at: start + .42, value: 1, easing: 'ease-in' }] })

function slide(id: string, title: string, headline: string, subhead: string, notes: string, duration: number, posterCueId: string, elements: SceneElement[], cues: SceneSlide['timeline']['cues'], tracks: SceneTrack[]): SceneSlide & { title: string, hidden: boolean, transition: 'none' | 'fade' } {
  const cueNotes = cues.map((cue, index) => index === 0
    ? `- ${cue.label}: 자동 시작`
    : `- ${cue.label}: 설명 후 클릭하여 다음 cue 진행`).join('\n')
  return { id, title, hidden: false, transition: id === 'gripgun-1' ? 'none' : 'fade', layoutId: 'visual-explainer', presenterNotes: `${notes}\n\n[발표 진행]\n${cueNotes}`, posterCueId, elements: [text('eyebrow', title.toUpperCase(), 110, 62, 900, 20, '#2563eb'), text('headline', headline, 110, 118, 1260, 48), text('subhead', subhead, 110, 220, 1120, 24, '#475569'), ...elements], timeline: { duration, cues, tracks } }
}

export function createGripGunPresentationDeck(): DeckDocumentV2 {
  const assets = createGripGunPrototypeScene().assets
  const slides = [
    slide('gripgun-1', '01 · Hitscan', 'GripGun은 총알을 날리지 않는다.', '입력 뒤 서버가 즉시 hit를 판정한다.', '한 장면의 전체 경로를 먼저 보여준다.', 10, 'result', [
      image('hero', 'beta-combat', 1040, 330, 670, 430), card('client', 'HUGH\nfire intent', 150, 500, 260, 150, '#2563eb'), connector('intent', 'client', 'right', 'server', 'left', '#2563eb'), card('server', 'SERVER\nvalidation', 610, 455, 350, 240, '#2563eb'), connector('ray', 'server', 'right', 'hit', 'left', '#f59e0b'), card('hit', 'FIRST\nblocking hit', 1310, 515, 300, 150, '#f59e0b'), text('result', '한 번의 판정 → 결과 cue', 585, 820, 760, 32, '#2563eb', 0), text('hud', 'LIVE COMBAT INPUT', 1100, 700, 490, 18, '#ffffff', 0),
    ], [{ id: 'intro', at: 0, mode: 'auto', label: '개요' }, { id: 'intent', at: 2, mode: 'click', label: '1. 입력' }, { id: 'trace', at: 4.5, mode: 'click', label: '2. 서버 trace' }, { id: 'result', at: 7.4, mode: 'hold', label: '3. hit 결과' }], [fade('hero-in', 'hero', 0, .45), fade('client-in', 'client', 0, .45), ...draw('intent-draw', 'intent', 2, 2.55), appear('server-in', 'server', 2.55), ...draw('ray-draw', 'ray', 4.5, 5.15), appear('hit-in', 'hit', 5.15), fade('result-in', 'result', 7, 7.4), fade('hud-in', 'hud', 7, 7.4), pulse('server-pulse', 'server', 2.55), pulse('hit-pulse', 'hit', 5.15)]),
    slide('gripgun-2', '02 · Not a projectile', '비행 projectile가 아니라 즉시 ray.', '가상의 탄환은 지우고 camera trace만 남긴다.', 'projectile, muzzle trace, corrective trace를 실제 동작처럼 말하지 않는다.', 7, 'ray', [
      image('hero', 'beta-hugh-hud', 850, 350, 850, 480), card('ghost', '×\nphysical projectile', 170, 470, 360, 180, '#ef4444'), text('cancel', 'NOT THE IMPLEMENTATION', 170, 700, 460, 24, '#ef4444', 0), card('camera', 'CAMERA\nPlayer View Point', 920, 455, 320, 180, '#2563eb'), connector('ray', 'camera', 'right', 'blocker', 'left', '#f59e0b'), card('blocker', 'FIRST\nblocking hit', 1430, 480, 270, 160, '#f59e0b'),
    ], [{ id: 'intro', at: 0, mode: 'auto', label: 'false mental model' }, { id: 'cancel', at: 1.5, mode: 'click', label: '1. cancel projectile' }, { id: 'ray', at: 3.3, mode: 'click', label: '2. draw ray' }, { id: 'hold', at: 5.2, mode: 'hold', label: '3. first blocker' }], [fade('hero-in', 'hero', 0, .45), fade('ghost-in', 'ghost', 0, .45), fade('cancel-in', 'cancel', 1.5, 1.8), fade('camera-in', 'camera', 3.3, 3.65), ...draw('ray-draw', 'ray', 3.3, 4), appear('blocker-in', 'blocker', 4), pulse('blocker-pulse', 'blocker', 4)]),
    slide('gripgun-3', '03 · Server authority', 'Client는 intent만 보낸다.', 'combat · weapon · cooldown · ammo gate는 server가 확정한다.', 'client mutation을 server authority와 혼동하지 않는다.', 9, 'gate', [
      image('hero', 'beta-hugh', 1240, 300, 380, 560), card('client', 'CLIENT\nrequest fire', 160, 480, 300, 160, '#2563eb'), connector('intent', 'client', 'right', 'server', 'left', '#2563eb'), card('server', 'SERVER\ncombat gate', 680, 405, 460, 300, '#2563eb'), text('gate', 'weapon  ·  cooldown  ·  ammo', 750, 570, 360, 25, '#2563eb', 0), text('commit', 'server confirms mutation', 660, 800, 560, 32, '#16a34a', 0),
    ], [{ id: 'intro', at: 0, mode: 'auto', label: 'request' }, { id: 'intent', at: 1.8, mode: 'click', label: '1. send intent' }, { id: 'gate', at: 3.5, mode: 'click', label: '2. validate' }, { id: 'commit', at: 5.8, mode: 'hold', label: '3. confirm' }], [fade('hero-in', 'hero', 0, .45), fade('client-in', 'client', 0, .45), pulse('client-pulse', 'client', .45), ...draw('intent-draw', 'intent', 1.8, 2.35), appear('server-in', 'server', 2.35), fade('gate-in', 'gate', 3.5, 4), pulse('server-pulse', 'server', 2.35), fade('commit-in', 'commit', 5.8, 6.2)]),
    slide('gripgun-4', '04 · Single Line Trace', 'Camera에서 첫 blocker까지 한 번.', 'trace는 첫 blocking hit에서 멈춘다.', 'Actor와 BoneName은 hit result에서 얻는다.', 9, 'impact', [
      image('hero', 'beta-hugh-hud', 610, 330, 800, 470), card('camera', 'CAMERA\norigin', 160, 475, 300, 170, '#2563eb'), connector('ray', 'camera', 'right', 'hit', 'left', '#f59e0b'), card('hit', 'FIRST BLOCKER\nActor + BoneName', 1280, 430, 390, 220, '#f59e0b'), text('impact', 'IMPACT\nlocation + normal', 1330, 750, 330, 38, '#f97316', 0),
    ], [{ id: 'intro', at: 0, mode: 'auto', label: 'camera origin' }, { id: 'ray', at: 2, mode: 'click', label: '1. line trace' }, { id: 'hit', at: 2.7, mode: 'click', label: '2. first blocker' }, { id: 'impact', at: 5.5, mode: 'hold', label: '3. impact input' }], [fade('hero-in', 'hero', 0, .45), fade('camera-in', 'camera', 0, .45), ...draw('ray-draw', 'ray', 2, 2.7), appear('hit-in', 'hit', 2.7), pulse('hit-pulse', 'hit', 2.7), fade('impact-in', 'impact', 5.5, 5.8)]),
    slide('gripgun-5', '05 · Damage / VFX', 'Damage와 presentation은 갈라진다.', 'DamageSpec은 health로, impact cue는 unreliable multicast로 이어진다.', 'VFX는 전달 보장이 아니다.', 10, 'badge', [
      card('hit', 'HIT RESULT', 760, 380, 400, 150, '#f59e0b'), connector('damage-route', 'hit', 'bottom', 'damage', 'top', '#16a34a'), card('damage', 'DamageSpec\nreceiver health', 490, 690, 380, 170, '#16a34a'), connector('vfx-route', 'hit', 'bottom', 'vfx', 'top', '#8b5cf6'), card('vfx', 'impact location + normal\nVFX multicast', 1070, 690, 440, 170, '#8b5cf6'), card('badge', 'UNRELIABLE ≠ delivery guarantee', 1070, 900, 440, 70, '#8b5cf6'),
    ], [{ id: 'intro', at: 0, mode: 'auto', label: 'hit result' }, { id: 'damage', at: 2, mode: 'click', label: '1. apply damage' }, { id: 'vfx', at: 4.5, mode: 'click', label: '2. broadcast cue' }, { id: 'badge', at: 6.8, mode: 'hold', label: '3. uncertainty' }], [fade('hit-in', 'hit', 0, .4), ...draw('damage-draw', 'damage-route', 2, 2.45), appear('damage-in', 'damage', 2.45), ...draw('vfx-draw', 'vfx-route', 4.5, 4.95), appear('vfx-in', 'vfx', 4.95), appear('badge-in', 'badge', 6.8), pulse('damage-pulse', 'damage', 2.45), pulse('vfx-pulse', 'vfx', 4.95)]),
    slide('gripgun-6', '06 · Build evidence', '실제 build에서 관찰한 hit 결과.', 'diagram의 결론을 current beta capture로 연결한다.', '정확한 사실과 실제 화면을 함께 제시한다.', 7, 'caption', [
      { id: 'evidence', type: 'image', assetId: 'beta-enemy-hit', transform: transform(500, 350, 920, 518, 5, 0), style: { borderRadius: 32, boxShadow: '0 30px 70px rgba(15,23,42,.28)', scale: .96 }, accessibilityLabel: 'Pragmata beta enemy hit evidence' }, text('caption', 'server hit 판정에서 파생된 impact presentation cue', 525, 900, 880, 28, '#2563eb', 0),
    ], [{ id: 'intro', at: 0, mode: 'auto', label: 'diagram 결론' }, { id: 'evidence', at: 1.5, mode: 'click', label: '1. 빌드 근거' }, { id: 'caption', at: 3.65, mode: 'hold', label: '2. 결론' }], [fade('evidence-in', 'evidence', 1.5, 2.25), pulse('evidence-pulse', 'evidence', 2.25), fade('caption-in', 'caption', 3.3, 3.65)]),
  ]
  const base = migrateSceneDocument(createGripGunPrototypeScene())
  return { ...base, id: 'gripgun-presentation-v2', metadata: { title: 'GripGun — Server-authoritative Line Trace' }, slides }
}
