import type { Deck, DeckSlide } from '../schema/deck.js'

export interface RenderOptions {
  readonly sourcePath?: string
}

export function renderDeckToSlidevMarkdown(deck: Deck, options: RenderOptions = {}): string {
  const [firstSlide, ...restSlides] = deck.slides
  const parts = [
    renderFirstSlide(deck, firstSlide, options),
    ...restSlides.map((slide, index) => renderSlide(slide, index + 1)),
  ]

  return `${parts.join('\n\n').trimEnd()}\n`
}

function renderFirstSlide(deck: Deck, slide: DeckSlide, options: RenderOptions): string {
  const lines = [
    '---',
    'theme: apple-basic',
    `title: ${yamlString(deck.title)}`,
    'fonts:',
    '  sans: "Pretendard Variable"',
    '  local: "Pretendard Variable"',
    '  provider: none',
    `layout: ${slide.layout ?? 'default'}`,
  ]

  if (deck.subtitle)
    lines.push(`subtitle: ${yamlString(deck.subtitle)}`)

  if (deck.author)
    lines.push(`author: ${yamlString(deck.author)}`)

  lines.push('info: |')
  lines.push('  Generated by LumaDeck.')
  lines.push('  Edit slides.md, components/, and styles/ directly for live production.')

  if (options.sourcePath)
    lines.push(`  Source deck: ${options.sourcePath}`)

  lines.push('---')
  lines.push('')
  lines.push('<!-- slide:1 -->')
  lines.push(...renderSlideBody(slide))
  lines.push(...renderNotes(slide))

  return lines.join('\n')
}

function renderSlide(slide: DeckSlide, index: number): string {
  const layout = slide.layout ?? 'default'
  const lines = [
    '---',
    `layout: ${layout}`,
    ...renderLayoutFrontmatter(slide),
    '---',
    '',
    `<!-- slide:${index + 1} -->`,
    ...renderSlideBody(slide),
    ...renderNotes(slide),
  ]

  return lines.join('\n').trimEnd()
}

function renderLayoutFrontmatter(slide: DeckSlide): string[] {
  const lines: string[] = []

  if (slide.image)
    lines.push(`image: ${yamlString(slide.image)}`)

  if (slide.images) {
    lines.push('images:')
    for (const image of slide.images)
      lines.push(`  - ${yamlString(image)}`)
  }

  return lines
}

function renderSlideBody(slide: DeckSlide): string[] {
  switch (slide.layout) {
    case 'intro':
    case 'intro-image':
    case 'intro-image-right':
    case 'section':
    case 'statement':
    case 'fact':
    case 'end':
      return renderTitleFirstSlide(slide)
    case 'quote':
      return renderQuoteSlide(slide)
    case 'bullets':
      return renderBulletsSlide(slide)
    case '3-images':
    case 'image':
    case 'image-right':
    case 'default':
    default:
      return renderDefaultSlide(slide)
  }
}

function renderTitleFirstSlide(slide: DeckSlide): string[] {
  const lines: string[] = []

  if (slide.title)
    lines.push(`# ${slide.title}`)

  if (slide.subtitle)
    lines.push('', slide.subtitle)

  lines.push(...renderBody(slide.body))

  return lines
}

function renderDefaultSlide(slide: DeckSlide): string[] {
  const lines: string[] = []

  if (slide.title)
    lines.push(`# ${slide.title}`, '')

  if (slide.subtitle)
    lines.push(`## ${slide.subtitle}`, '')

  lines.push(...renderBody(slide.body))

  return lines
}

function renderBulletsSlide(slide: DeckSlide): string[] {
  const lines: string[] = []

  if (slide.title)
    lines.push(`# ${slide.title}`, '')

  const body = Array.isArray(slide.body) ? slide.body : splitBodyLines(slide.body)

  for (const item of body)
    lines.push(`- ${item}`)

  return lines
}

function renderQuoteSlide(slide: DeckSlide): string[] {
  const lines: string[] = []
  const quote = slide.quote ?? (typeof slide.body === 'string' ? slide.body : undefined)

  if (quote)
    lines.push(`> ${quote}`)

  if (slide.attribution)
    lines.push('', `- ${slide.attribution}`)

  return lines
}

function renderBody(body: DeckSlide['body']): string[] {
  if (!body)
    return []

  if (Array.isArray(body))
    return body.map(item => `- ${item}`)

  return splitBodyLines(body)
}

function splitBodyLines(body?: string): string[] {
  return body?.split(/\r?\n/).map(line => line.trimEnd()).filter(Boolean) ?? []
}

function renderNotes(slide: DeckSlide): string[] {
  if (!slide.notes)
    return []

  return [
    '',
    '<!--',
    slide.notes,
    '-->',
  ]
}

function yamlString(value: string): string {
  return JSON.stringify(value)
}
